export const ADD_PERSON_TO_FAVORITE = 'ADD_PERSON_TO_FAVORITE'
export const REMOVE_PERSON_FROM_FAVORITE = 'REMOVE_PERSON_FROM_FAVORITE'

export const ADD_PLANET_TO_FAVORITE = 'ADD_PLANET_TO_FAVORITE'
export const REMOVE_PLANET_FROM_FAVORITE = 'REMOVE_PLANET_FROM_FAVORITE'